project:
  type: website
  output-dir: docs

website:
  title: "PORTFOLIO"
  navbar:
    left:
      - text: "About"
        file: about.qmd
      - text: "Contact"
        file: contact.qmd
      - Projects.qmd
      

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual